apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: devops-dev

resources:
  - namespace.yaml
  - ../../base

images:
  - name: registry.example.invalid/devops-platform/console
    newTag: scaffold
  - name: registry.example.invalid/devops-platform/control-plane
    newTag: scaffold
  - name: registry.example.invalid/devops-platform/runner
    newTag: scaffold

replicas:
  - name: console
    count: 1
  - name: control-plane
    count: 1
  - name: runner
    count: 1
